/*
 * ConstantParamAndUseFunction.h
 *
 *  Created on: 2021年11月9日
 *      Author: Fernando.Wang.HHW
 */

#ifndef INC_CONSTANTPARAMANDUSEFUNCTION_H_
#define INC_CONSTANTPARAMANDUSEFUNCTION_H_

#define USE_FUNCTION 1
#define UNUSE_FUNCTION 0

//Constant Parameter
#define DRIVE_PROPULSION_TOLERANCE	1.0f
#define GUARANTEED_VBUS_FOR_PERFORMANCE 42.0f
#define PHASE_LOSS_SPEED 125.663706144f //300RPM/60*4*2PI=125.663706144

#define Factor_to_cal_power_from_dq 1.5f
#define Root_of_One_Third 0.577350269f

#define JUDGE_FUNCTION_DELAY UNUSE_FUNCTION
#define MEASURE_CPU_LOAD USE_FUNCTION
#define MEASURE_CPU_LOAD_CURRENTLOOP USE_FUNCTION
#define MEASURE_CPU_LOAD_PLCLOOP USE_FUNCTION

#define MOTOR_P0 	1
#define MOTOR_P1_3 	0
#define MOTOR_STAGE MOTOR_P0

//Function status of use
#define USE_CALC_SUM_ROOT UNUSE_FUNCTION
#define USE_THERMAL_DERATING USE_FUNCTION
#define USE_DATA_RECORD UNUSE_FUNCTION
#define USE_UART_COMMUNICATION UNUSE_FUNCTION
#define USE_THROTTLE_CALIBRATION USE_FUNCTION
#define USE_CURRENT_CALIBRATION USE_FUNCTION
#define USE_VOLTAGE_CALIBRATION UNUSE_FUNCTION

#define USE_HIGH_RESO_MOTOR_TABLE UNUSE_FUNCTION

#define USE_INIT_HIGH_SECURITY USE_FUNCTION

#define USE_REVERVE_MR_DIRECTION UNUSE_FUNCTION
#define USE_UVW_AS_FORWARD_DIRECTION UNUSE_FUNCTION

#define USE_DATA_RECORDER USE_FUNCTION

#define USE_MOTOR_CTRL_DEBUG UNUSE_FUNCTION

#define USE_COMPLEX_VECTOR_DCP USE_FUNCTION

#endif /* INC_CONSTANTPARAMANDUSEFUNCTION_H_ */
